# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USDAIngredient',
            fields=[
                ('food_id', models.CharField(max_length=10, serialize=False, primary_key=True)),
                ('name', models.TextField()),
                ('water', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('energy_kc', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('protein_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('protein_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('protein_percent_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('total_fat_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('total_fat_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('percent_fat_calories', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('carbohydrate_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('carbohydrate_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('percent_calories_from_cho', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('fiber_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('fiber_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('calcium_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('calcium_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('copper_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('copper_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('iron_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('iron_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('magnesium_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('magnesium_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('manganese_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('manganese_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('phosphorus_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('phosphorus_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('potassium_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('potassium_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('selenium_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('selenium_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('sodium_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('sodium_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('zinc_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('zinc_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_a_iu_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_a_iu_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_a_re_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_a_re_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('b_carotene_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('b_carotene_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('a_carotene_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('cryptoxanthin_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('lycopene_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('lutein_zeaxanthin_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_d_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_d_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('thiamin_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('thiamin_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('riboflavin_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('riboflavin_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vit_b6_wtpyridoxine', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vit_b6_calpyridoxine', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_b12_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_b12_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_c_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_c_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_e_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_e_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_k_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('vitamin_k_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('folate_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('folate_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('niacin_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('niacin_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('pantothenic_acid_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('pantothenic_acid_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('cholesterol_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('cholesterol_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('fa_sat_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('fa_sat_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('butanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('butanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('hexanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('hexanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('octanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('octanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('decanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('decanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('dodecanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('dodecanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tetradecanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tetradecanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('pentadecanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('pentadecanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('hexadecanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('hexadecanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('heptadecanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('heptadecanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('octadecanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('octadecanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('eicosanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('eicosanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('docosanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('docosanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tetracosanoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tetracosanoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('monounsaturated_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('monounsaturated_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tetradecenoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tetradecenoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('hexadecenoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('hexadecenoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('octadecenoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('octadecenoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('eicosenoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('eicosenoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('docosenoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('docosenoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('fa_poly_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('fa_poly_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('la_wt_octadecadienoic', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('la_cal_octadecadienoic', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('ala_wt_octadecatrienoic', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('ala_cal_octadecatrienoic', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('octadecatetraenoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('octadecatetraenoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('eicosatetraenoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('eicosatetraenoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('epa_wt_eicosapentaenoic', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('epa_cal_eicosapentaenoic', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('docosapentaenoic_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('docosapentaenoic_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('dha_wt_docosahexaenoic', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('dha_cal_docosahexaenoic', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('phytosterols_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('phytosterols_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('histidine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('histidine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('isoleucine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('isoleucine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('leucine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('leucine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('lysine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('lysine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('methionine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('methionine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('phenylalanine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('phenylalanine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('threonine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('threonine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tryptophan_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tryptophan_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tyrosine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('tyrosine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('valine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('valine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('alanine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('alanine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('arginine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('arginine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('aspartic_acid_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('aspartic_acid_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('cystine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('cystine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('glutamic_acid_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('glutamic_acid_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('glycine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('glycine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('proline_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('proline_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('serine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('serine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('total_isoflavones', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('daidzein', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('genistein', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('glycitein', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('ash_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('ash_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('percent_refuse', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('caffeine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('caffeine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('theobromine_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('theobromine_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('alcohol_wt', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('alcohol_cal', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
                ('total_sugar', models.DecimalField(null=True, max_digits=20, decimal_places=10)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
