from django.db import models
from django.contrib.auth.models import User


class USDAIngredient(models.Model):

    ''' Autogenerated model file csvimport Mon Jan 25 06:33:52 2016 '''

    food_id = models.AutoField(primary_key=True)

    food_description = models.CharField(max_length=2000,null=False, blank=True)

    energy_kc = models.IntegerField(null=True, blank=True)

    protein_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    total_fat_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    carbohydrate_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    fiber_per_wt = models.DecimalField(null=True, blank=True, max_digits=1003, decimal_places=10)

    calcium_per_wt = models.DecimalField(max_digits=1003, decimal_places=10, null=True, blank=True)
    copper_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    iron_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    magnesium_per_wt = models.DecimalField(max_digits=1003, decimal_places=10, null=True, blank=True)

    potassium_per_wt = models.DecimalField(max_digits=1003, decimal_places=10, null=True, blank=True)

    zinc_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    vitamin_a_iu_per_wt = models.DecimalField(max_digits=1003, decimal_places=10, null=True, blank=True)

    vitamin_d_per_wt = models.DecimalField(null=True, blank=True, max_digits=1003, decimal_places=10)

    thiamin_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    riboflavin_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    vit_b6_per_wt_pyridoxine = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    vitamin_b12_per_wt = models.DecimalField(null=True, max_digits=1006, decimal_places=10, blank=True)

    folate_per_wt = models.DecimalField(max_digits=1003, decimal_places=10,  null=True, blank=True)

    niacin_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    pantothenic_acid_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    vitamin_c_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    vitamin_e_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    vitamin_k_per_wt = models.DecimalField(max_digits=1003, decimal_places=10, null=True, blank=True)

    fa_sat_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    monounsaturated_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    fa_poly_per_wt = models.DecimalField(null=True, max_digits=1003, decimal_places=10, blank=True)

    total_sugar = models.DecimalField(null=True, blank=True,max_digits=1003, decimal_places=10)

    class Meta:
        managed = False
        db_table = u'"csvimport_"'

    def __unicode__(self):
    	return self.food_description
